### ISSUE TITLE
请问"vector 不是模板"如何解决

### ISSUE THREAD

**Issue by Rosonlee** [LeetCode-OpenSource/vscode-leetcode#623]
![image](https://user-images.githubusercontent.com/34086972/91689919-a0e25d00-eb97-11ea-942e-d8c613e5ef24.png)
网上搜到的加头文件解决效率好低

**Comment by jdneo** [comment]
This extension does not provide any language support related features.

I guess you get such error because you installed the related extensions. (for example, c++ extension)

Unfortunately, there is nothing we can do about this so far. Since this is out of the scope of the LeetCode extension.

**Comment by Nikita240** [comment]
@jdneo I disagree. 

You could provide an include to a header file that contains all the symbols that LeetCode uses. 

The leetcode-cli cpp.run plugin already has all the information to do this since it puts all of the symbols definitions in the run file when you run a local test. 

If you want to see for yourself, start a sample problem and run `leetcode test 001.two-sum.cpp --local`. Then take a look at the generated `.tmp.cpp.run.cpp` file. 

The file contains all of the LeetCode specific symbols, a main method, and your `Solution` class copy-pasted.

**Comment by Nikita240** [comment]
Also, please note that without doing the trick I discussed above, there is no way to debug your program.
