### ISSUE TITLE
連cookie都無法登入了？

### ISSUE THREAD

**Issue by zjimf** [LeetCode-OpenSource/vscode-leetcode#908]
以往用cookie都能順利登入，但今天卻不行了，有人遇到一樣的問題嗎？

錯誤訊息顯示如下
let s = args.map(x => x.toString()).join(' ');
                                        ^

**Comment by ntzb** [comment]
same

**Comment by willhpkns** [comment]
Same issue

**Comment by laskjd** [comment]
same.
trying to log in via github doesn't work also

**Comment by gcobc26744** [comment]
same too，bro . I try all night .
but my problem is that I can't donwolad the leetcode question

**Comment by kylelau519** [comment]
cannot login with GitHub, able to submit within past 24 hours but not now.

**Comment by MyEnthusiastic** [comment]
same issue, not able to log in both with cookie, linkedin, as well as github

**Comment by casperking666** [comment]
thought it was just me, was even working in the morning, stopped working in the afternoon

**Comment by jasoncyu** [comment]
yeah same logging in with github and cookie is no longer working as of a few hours ago

**Comment by PANhuihuihuihui** [comment]
same issue!

**Comment by zjimf** [comment]
this is a very helpful extension, hope it can be fixed soon

**Comment by zjimf** [comment]
guys I can log in now

**Comment by g-akshay** [comment]
1. change below value and take latest from browser
(get the cookie value from the network requests  -> request headers), skip the "expiry attribute"
2. close the browser
3. restart VS code
4. login with cookie
5. enter below value for username and cookie value both

Value:
csrftoken=XYZ; LEETCODE_SESSION=xyz;_dd_s=rum=0

**Comment by huikinglam02gmail** [comment]
This bug comes up again....

**Comment by billpku** [comment]
I'm experiencing the same issue; it used to work well before, but now I can't log in with a cookie anymore. 

I will try the method suggested by @g-akshay.If it's successful, I will provide an update.

**Comment by HOZH** [comment]
any luck?

**Comment by jasoncyu** [comment]
I also had this issue come up when @HOZH and @billpku experienced it. I did some debugging, and it looks like when leetcode tries to submit the solution, an HTML page was sent as a response, saying something like "hang on a second" in the title. I just console log'ed the response html and wasn't able to open it in a browser because the linked javascript couldnt' be found. I tried linkedin, github, and cookie logins while this issue was occurring and nothing worked. Only thing that worked was waiting two days, just like @billpku experienced. And now that the issue is gone, signing in with any method is successful
